CREATE TABLE `exchanges` (
  `exchange` varchar(45) DEFAULT NULL,
  `exchangename` varchar(45) DEFAULT NULL,
  KEY `exchange` (`exchange`),
  KEY `exchangename` (`exchangename`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `exchanges` (`exchange`, `exchangename`) VALUES
('abcc',	'ABCC'),
('acx',	'ACX'),
('aex',	'AEX'),
('airswap',	'AirSwap'),
('allbit',	'Allbit'),
('allcoin',	'Allcoin'),
('alterdice',	'AlterDice'),
('altilly',	'Altilly'),
('altmarkets',	'Altmarkets'),
('anx',	'ANX'),
('aphelion',	'Aphelion'),
('atomars',	'Atomars'),
('axnet',	'AXNET'),
('b2bx',	'B2BX'),
('bamboo_relay',	'Bamboo Relay'),
('bancor',	'Bancor Network'),
('bankera',	'Bankera'),
('bcex',	'BCEX'),
('beaxy',	'Beaxy'),
('bgogo',	'Bgogo'),
('bibox',	'Bibox'),
('bigmarkets',	'BIG markets'),
('bigone',	'BigONE'),
('bihodl',	'BiHODL '),
('biki',	'Biki'),
('bilaxy',	'Bilaxy'),
('binance',	'Binance'),
('binance_dex',	'Binance DEX'),
('binance_futures',	'Binance Futures'),
('binance_jersey',	'Binance Jersey'),
('binance_us',	'Binance US'),
('bione',	'Bione'),
('birake',	'Birake'),
('bisq',	'Bisq'),
('bit2c',	'Bit2c'),
('bitalong',	'Bitalong'),
('bitasset',	'BitAsset'),
('bitbank',	'Bitbank'),
('bitbay',	'BitBay'),
('bitbegin',	'Bitbegin'),
('bitbox',	'BITBOX'),
('bitc3',	'Bitc3'),
('bitci',	'Bitci'),
('bitcoin_com',	'Bitcoin.com'),
('bitex',	'Bitex.la'),
('bitexbook',	'BITEXBOOK'),
('bitexlive',	'Bitexlive'),
('bitfex',	'Bitfex'),
('bitfinex',	'Bitfinex'),
('bitflyer',	'bitFlyer'),
('bitflyer_futures',	'Bitflyer Futures'),
('bitforex',	'Bitforex'),
('bitforex_futures',	'Bitforex Futures'),
('bithash',	'BitHash'),
('bitholic',	'Bithumb Singapore'),
('bithumb',	'Bithumb'),
('bithumb_global',	'Bithumb Global'),
('bitinfi',	'Bitinfi'),
('bitker',	'BITKER'),
('bitkonan',	'BitKonan'),
('bitkub',	'Bitkub'),
('bitlish',	'Bitlish'),
('bitmart',	'BitMart'),
('bitmax',	'BitMax'),
('bitmesh',	'Bitmesh'),
('bitmex',	'Bitmex'),
('bitoffer',	'Bitoffer'),
('bitonbay',	'BitOnBay'),
('bitopro',	'BitoPro'),
('bitrabbit',	'BitRabbit'),
('bitrue',	'Bitrue'),
('bits_blockchain',	'Bits Blockchain'),
('bitsdaq',	'Bitsdaq'),
('bitshares_assets',	'Bitshares Assets'),
('bitso',	'Bitso'),
('bitsonic',	'Bitsonic'),
('bitstamp',	'Bitstamp'),
('bitsten',	'Bitsten'),
('bitstorage',	'BitStorage'),
('bittrex',	'Bittrex'),
('bit_z',	'Bit-Z'),
('bkex',	'Bkex'),
('bleutrade',	'bleutrade'),
('blockonix',	'Blockonix'),
('boa',	'BOA Exchange'),
('braziliex',	'Braziliex'),
('btc_alpha',	'BTC-Alpha'),
('btcbox',	'BTCBOX'),
('btcc',	'BTCC'),
('btcexa',	'BTCEXA'),
('btc_exchange',	'Btc Exchange'),
('btcmarkets',	'BTCMarkets'),
('btcnext',	'BTCNEXT'),
('btcsquare',	'BTCSquare'),
('btc_trade_ua',	'BTC Trade UA'),
('btcturk',	'BTCTurk'),
('btse',	'BTSE'),
('buyucoin',	'BuyUcoin'),
('bw',	'BW.com'),
('bx_thailand',	'BX Thailand'),
('bybit',	'Bybit'),
('c2cx',	'C2CX'),
('cashierest',	'Cashierest'),
('catex',	'Catex'),
('cbx',	'CBX'),
('ccex',	'C-CEX'),
('ccx',	'CCXCanada'),
('cex',	'CEX.IO'),
('cezex',	'Cezex'),
('chainex',	'ChainEX'),
('chainrift',	'Chainrift'),
('chaoex',	'CHAOEX'),
('citex',	'CITEX'),
('cme_futures',	'CME Bitcoin Futures'),
('cobinhood',	'Cobinhood'),
('codex',	'CODEX'),
('coinall',	'CoinAll'),
('coinasset',	'CoinAsset'),
('coinbe',	'Coinbe'),
('coinbene',	'CoinBene'),
('coinbig',	'COINBIG'),
('coinbit',	'Coinbit'),
('coinchangex',	'Coinchangex'),
('coincheck',	'Coincheck'),
('coindeal',	'Coindeal'),
('coindirect',	'CoinDirect'),
('coineal',	'Coineal'),
('coin_egg',	'CoinEgg'),
('coinex',	'CoinEx'),
('coin_exchange',	'CoinExchange.io'),
('coinfalcon',	'Coinfalcon'),
('coinfield',	'Coinfield'),
('coinfinit',	'Coinfinit'),
('coinflex',	'CoinFLEX'),
('coinflex_futures',	'CoinFLEX (Futures)'),
('coingi',	'Coingi'),
('coinhe',	'CoinHe'),
('coinhub',	'Coinhub'),
('coinjar',	'CoinJar Exchange'),
('coinlim',	'Coinlim'),
('coin_metro',	'Coinmetro'),
('coinmex',	'CoinMex'),
('coinnest',	'CoinNest'),
('coinone',	'Coinone'),
('coinpark',	'Coinpark'),
('coinplace',	'Coinplace'),
('coinsbank',	'Coinsbank'),
('coinsbit',	'Coinsbit'),
('coinsuper',	'Coinsuper'),
('cointiger',	'CoinTiger'),
('coinxpro',	'COINX.PRO'),
('coinzest',	'Coinzest'),
('coinzo',	'Coinzo'),
('coss',	'COSS'),
('c_patex',	'C-Patex'),
('cpdax',	'CPDAX'),
('credoex',	'CredoEx'),
('crex24',	'CREX24'),
('crxzone',	'CRXzone'),
('cryptaldash',	'CryptalDash'),
('cryptex',	'Cryptex'),
('crypto_bridge',	'CryptoBridge'),
('cryptology',	'Cryptology'),
('cryptonit',	'Cryptonit'),
('crytrex',	'CryTrEx'),
('cybex',	'Cybex DEX'),
('dach_exchange',	'Dach Exchange'),
('dakuce',	'Dakuce'),
('darb_finance',	'Darb Finance'),
('daybit',	'Daybit'),
('dcoin',	'Dcoin'),
('ddex',	'DDEX'),
('deribit',	'Deribit'),
('dextop',	'DEx.top'),
('dextrade',	'Dex-Trade'),
('dflow',	'Dflow'),
('digifinex',	'Digifinex'),
('digitalprice',	'DigitalPrice'),
('dobitrade',	'Dobitrade'),
('dove_wallet',	'Dove Wallet'),
('dragonex',	'DragonEx'),
('dsx',	'DSX'),
('dydx',	'dYdX'),
('ecxx',	'Ecxx'),
('eosex',	'EOSex'),
('escodex',	'Escodex'),
('eterbase',	'Eterbase'),
('etherflyer',	'EtherFlyer'),
('ethex',	'Ethex'),
('ethfinex',	'Ethfinex'),
('everbloom',	'Everbloom'),
('exmarkets',	'ExMarkets'),
('exmo',	'EXMO'),
('exnce',	'EXNCE'),
('exrates',	'Exrates'),
('extstock',	'ExtStock'),
('exx',	'EXX'),
('f1cx',	'F1CX'),
('fatbtc',	'FatBTC'),
('fcoin',	'FCoin'),
('fex',	'FEX'),
('financex',	'FinanceX'),
('finexbox',	'FinexBox'),
('fisco',	'Fisco'),
('floatsv',	'Float SV'),
('forkdelta',	'ForkDelta'),
('freiexchange',	'Freiexchange'),
('ftx',	'FTX'),
('ftx_spot',	'FTX (Spot)'),
('fubt',	'FUBT'),
('gate',	'Gate.io'),
('gate_futures',	'Gate.io (Futures)'),
('gbx',	'Gibraltar Blockchain Exchange'),
('gdac',	'GDAC'),
('gdax',	'Coinbase Pro'),
('gemini',	'Gemini'),
('getbtc',	'GetBTC'),
('gmo_japan',	'GMO Japan'),
('gmo_japan_futures',	'GMO Japan (Futures)'),
('gobaba',	'Gobaba'),
('go_exchange',	'Go Exchange'),
('gopax',	'GoPax'),
('graviex',	'Graviex'),
('hb_top',	'Hb.top'),
('hitbtc',	'HitBTC'),
('hotbit',	'Hotbit'),
('hpx',	'HPX'),
('hubi',	'Hubi'),
('huobi',	'Huobi Global'),
('huobi_dm',	'Huobi DM'),
('huobi_japan',	'Huobi Japan'),
('huobi_korea',	'Huobi Korea'),
('huobi_us',	'Huobi US (HBUS)'),
('ice3x',	'Ice3x'),
('idax',	'Idax'),
('idcm',	'IDCM'),
('idex',	'Idex'),
('incorex',	'IncoreX'),
('independent_reserve',	'Independent Reserve'),
('indodax',	'Indodax'),
('infinity_coin',	'Infinity Coin'),
('instantbitex',	'Instant Bitex'),
('iqfinex',	'IQFinex'),
('ironex',	'Ironex'),
('itbit',	'itBit'),
('jex',	'Binance JEX'),
('jex_futures',	'Binance JEX (Futures)'),
('joyso',	'Joyso'),
('kairex',	'KAiREX'),
('kkcoin',	'KKCoin'),
('k_kex',	'KKEX'),
('koinok',	'Koinok'),
('koinx',	'Koinx'),
('korbit',	'Korbit'),
('kraken',	'Kraken'),
('kraken_futures',	'Kraken (Futures)'),
('kryptono',	'Kryptono'),
('kucoin',	'KuCoin'),
('kumex',	'Kumex'),
('kuna',	'Kuna Exchange'),
('kyber_network',	'Kyber Network'),
('lakebtc',	'LakeBTC'),
('latoken',	'LATOKEN'),
('lbank',	'Lbank'),
('letsdocoinz',	'Letsdocoinz'),
('livecoin',	'Livecoin'),
('localtrade',	'LocalTrade'),
('luno',	'Luno'),
('lykke',	'Lykke'),
('max_maicoin',	'Max Maicoin'),
('mercado_bitcoin',	'Mercado Bitcoin'),
('mercatox',	'Mercatox'),
('mercuriex',	'MercuriEx'),
('mxc',	'MXC'),
('nanu_exchange',	'Nanu Exchange'),
('nash',	'Nash'),
('neblidex',	'Neblidex'),
('negociecoins',	'Negociecoins'),
('neraex',	'Neraex'),
('newdex',	'Newdex'),
('nexybit',	'Nexybit'),
('ninecoin',	'9coin'),
('nlexch',	'NLexch'),
('novadax',	'NovaDAX'),
('novadex',	'Novadex'),
('novaexchange',	'Nova Exchange'),
('oceanex',	'Oceanex'),
('oex',	'OEX'),
('okcoin',	'OKCoin'),
('okex',	'OKEx'),
('okex_korea',	'OKEx Korea'),
('okex_swap',	'OKEx (Futures)'),
('omgfin',	'Omgfin'),
('omnitrade',	'OmniTrade'),
('ooobtc',	'OOOBTC'),
('openledger',	'OpenLedger DEX'),
('orderbook',	'Orderbook.io'),
('ore_bz',	'Ore BZ'),
('otcbtc',	'OTCBTC'),
('ovex',	'Ovex'),
('p2pb2b',	'P2PB2B'),
('paribu',	'Paribu'),
('paroexchange',	'Paro Exchange'),
('paymium',	'Paymium'),
('piexgo',	'Piexgo'),
('poloniex',	'Poloniex'),
('probit',	'Probit'),
('purcow',	'Purcow'),
('qbtc',	'QBTC'),
('qtrade',	'qTrade'),
('quoine',	'Liquid'),
('radar_relay',	'Radar Relay'),
('raisex',	'Raisex'),
('rfinex',	'Rfinex'),
('safe_trade',	'SafeTrade'),
('satoexchange',	'SatoExchange'),
('sato_wallet_ex',	'SatowalletEx'),
('saturn_network',	'Saturn Network'),
('secondbtc',	'SecondBTC'),
('shortex',	'Shortex'),
('simex',	'Simex'),
('sistemkoin',	'Sistemkoin'),
('six_x',	'6x'),
('south_xchange',	'SouthXchange'),
('stake_cube',	'StakeCube'),
('stellar_term',	'StellarTerm'),
('stocks_exchange',	'STEX'),
('swiftex',	'Swiftex'),
('switcheo',	'Switcheo'),
('syex',	'Shangya Exchange'),
('synthetix',	'Synthetix Exchange'),
('tdax',	'Satang Pro'),
('therocktrading',	'TheRockTrading'),
('thetokenstore',	'Token.Store'),
('thinkbit',	'ThinkBit Pro'),
('three_xbit',	'3XBIT'),
('tideal',	'Tideal'),
('tidebit',	'Tidebit'),
('tidex',	'Tidex'),
('tokenize',	'Tokenize'),
('tokenjar',	'TokenJar'),
('tokenomy',	'Tokenomy'),
('tokens_net',	'TokensNet'),
('tokok',	'TOKOK'),
('tokpie',	'Tokpie'),
('topbtc',	'TopBTC'),
('tradeio',	'Trade.io'),
('trade_ogre',	'TradeOgre'),
('trade_satoshi',	'Trade Satoshi'),
('troca_ninja',	'Troca.Ninja'),
('tron_trade',	'TronTrade'),
('trx_market',	'TRXMarket'),
('tux_exchange',	'Tux Exchange'),
('txbit',	'Txbit'),
('uex',	'UEX'),
('uniswap',	'Uniswap'),
('upbit',	'Upbit'),
('vbitex',	'Vbitex'),
('vebitcoin',	'Vebitcoin'),
('velic',	'Velic'),
('vindax',	'Vindax'),
('vinex',	'Vinex'),
('waves',	'Waves Platform'),
('wazirx',	'WazirX'),
('whale_ex',	'WhaleEx'),
('whitebit',	'Whitebit'),
('worldcore',	'Worldcore'),
('xfutures',	'Xfutures'),
('xt',	'XT'),
('yobit',	'YoBit'),
('yunex',	'Yunex.io'),
('zaif',	'Zaif'),
('zb',	'ZB'),
('zbg',	'ZBG'),
('zbmega',	'ZB Mega'),
('zebpay',	'Zebpay'),
('zg',	'ZG.com'),
('zgtop',	'ZG.TOP');
